---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    author: sai
    type: db
spec:
  containers:
    - name: mysql
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: sai





...
