---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    type: ci-cd
    author: Sai
spec:
  containers:
    - name: my-jenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9090



...
